structure:
  readme: ./introduction.md
  summary: ./SUMMARY.md

redirects:
  developer/guide/: ./getting-started.md
  developer/guide: ./getting-started.md
  developer/guide/train: ./getting-started.md
  advanced/models: ./api-guide/model/clarifai-models.md
  api-guide/inputs: ./api-guide/data/README.md
  api-guide/inputs/create-get-update-delete: ./api-guide/data/create-get-update-delete.md
  portal-guide/model/model-types.md: ./portal-guide/model/model-types.md
  portal-guide/pdata_management: ./portal-guide/data/README.md
  portal-guide/portal_overview: ./portal-guide/portal-overview/readme.md
  v/v6.8/portal-guide/data/csv-and-tsv: ./portal-guide/data/csv-and-tsv.md
  api-guide/search/search:	./api-guide/search/rank-filter-combine-or-negate.md
  api-guide/walkthroughs: ./how-to/api/custom-model-walkthrough.md
  api-guide/walkthroughs/custom-model-walkthrough: ./how-to/api/custom-model-walkthrough.md
  api-guide/walkthroughs/custom-text-model-walkthrough: ./how-to/api/custom-text-model-walkthrough.md
  api-guide/walkthroughs/visual-text-recognition-walkthrough: ./how-to/api/visual-text-recognition-walkthrough.md
  getting-started/authentication/sso: ./getting-started/authentication/2-factor-authentication.md
  portal-guide/collectors/collectors: ./portal-guide/data/collectors.md
  portal-guide/data/collectors/collectors: ./portal-guide/data/collectors.md
  portal-guide/walkthroughs: ./how-to/portal/pcustom-model-walkthrough.md
  getting-started/applications: ./clarifai-basics/applications.md
  getting-started/applications/create-an-application: ./clarifai-basics/applications/create-an-application.md
  getting-started/applications/application-settings: ./clarifai-basics/applications/application-settings.md
  getting-started/applications/collaboration: ./clarifai-basics/applications/collaboration.md
  /getting-started/authentication: ./clarifai-basics/authentication.md
  /getting-started/authentication/app-specific-api-keys: ./clarifai-basics/authentication/app-specific-api-keys.md
  /getting-started/authentication/personal-access-tokens: ./clarifai-basics/authentication/personal-access-tokens.md
  /getting-started/authentication/scopes: ./clarifai-basics/authentication/scopes.md
  /getting-started/authentication/authorize: ./clarifai-basics/authentication/authorize.md
  /getting-started/authentication/2-factor-authentication: ./clarifai-basics/authentication/2-factor-authentication.md
  /getting-started/authentication/rbac: ./clarifai-basics/authentication/rbac.md
  /getting-started/glossary: ./clarifai-basics/glossary.md
