structure:
  readme: ./introduction.md
  summary: ./SUMMARY.md

redirects:
  developer/guide/: ./getting-started.md
  developer/guide: ./getting-started.md
  developer/guide/train: ./getting-started.md
