name: Test code examples

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        cd tests
        pip install -r requirements.txt
    - name: Run code examples tests
      run: |
        cd tests
        python run_code_examples_tests.py
